//! Replays the arithmetic of the reference's arbitrary-precision library.
//!
//! Rendering was pinned first and is the easy half: one value, one answer.
//! Arithmetic has a configuration, and the configuration is where a port goes
//! wrong quietly -- rounding a sum that should be exact, or failing to round a
//! quotient that should not be.
//!
//! The fixture is generated by `tools/cyberchef-oracle/bignumber.mjs` from the
//! library inside the pinned checkout, and carries the settings it was
//! produced under so a reader can see which rules the answers follow.

#![cfg(feature = "bignum")]

use ferrosift_model::DecimalValue;
use ferrosift_operations::jscompat_testing::bignumber;
use serde::Deserialize;

const FIXTURE: &str = include_str!("fixtures/bignumber.json");

#[derive(Deserialize)]
struct Fixture {
    settings: Settings,
    binary: Vec<Binary>,
    unary: Vec<Unary>,
    lists: Vec<List>,
    base_parses: Vec<BaseParse>,
    base_renders: Vec<BaseRender>,
}

/// One reading of a number written in another base.
///
/// `fixed` is `null` where the reference throws. A refusal is not a value, and
/// recording it as one -- as not-a-number, say -- would let a port that
/// answered instead of refusing pass.
#[derive(Deserialize)]
struct BaseParse {
    text: String,
    base: u32,
    fixed: Option<String>,
}

/// One writing of a number in another base.
#[derive(Deserialize)]
struct BaseRender {
    input: String,
    base: u32,
    written: Option<String>,
}

#[derive(Deserialize)]
struct Settings {
    decimal_places: u32,
    rounding_mode: u32,
    modulo_mode: u32,
}

#[derive(Deserialize)]
struct Binary {
    left: String,
    right: String,
    plus: String,
    minus: String,
    times: String,
    div: String,
    #[serde(rename = "mod")]
    remainder: String,
}

#[derive(Deserialize)]
struct Unary {
    input: String,
    sqrt: String,
    negated: String,
    absolute: String,
}

#[derive(Deserialize)]
struct List {
    values: Vec<String>,
    sum: String,
    mean: String,
    median: String,
}

fn fixture() -> Fixture {
    serde_json::from_str(FIXTURE).expect("the oracle's fixture parses")
}

#[test]
fn the_settings_are_the_ones_this_port_was_written_against() {
    // If the reference is ever reconfigured, every answer below changes and
    // the failures would look like arithmetic bugs. Checking the settings
    // first turns that into one clear failure instead of thirty confusing
    // ones.
    let settings = fixture().settings;
    assert_eq!(settings.decimal_places, 20, "places carried");
    assert_eq!(settings.rounding_mode, 4, "half away from zero");
    assert_eq!(settings.modulo_mode, 1, "truncated, dividend's sign");
}

#[test]
fn every_binary_operation_agrees_with_the_reference() {
    for case in fixture().binary {
        let left = DecimalValue::parse(&case.left);
        let right = DecimalValue::parse(&case.right);
        let context = format!("{} and {}", case.left, case.right);

        assert_eq!(
            bignumber::plus(&left, &right).to_fixed(),
            case.plus,
            "adding {context}"
        );
        assert_eq!(
            bignumber::minus(&left, &right).to_fixed(),
            case.minus,
            "subtracting {context}"
        );
        assert_eq!(
            bignumber::times(&left, &right).to_fixed(),
            case.times,
            "multiplying {context}"
        );
        assert_eq!(
            bignumber::divide(&left, &right).to_fixed(),
            case.div,
            "dividing {context}"
        );
        assert_eq!(
            bignumber::modulo(&left, &right).to_fixed(),
            case.remainder,
            "the remainder of {context}"
        );
    }
}

#[test]
fn every_unary_operation_agrees_with_the_reference() {
    for case in fixture().unary {
        let value = DecimalValue::parse(&case.input);
        assert_eq!(
            bignumber::square_root(&value).to_fixed(),
            case.sqrt,
            "the root of {}",
            case.input
        );
        assert_eq!(
            bignumber::negate(&value).to_fixed(),
            case.negated,
            "negating {}",
            case.input
        );
        assert_eq!(
            bignumber::absolute(&value).to_fixed(),
            case.absolute,
            "the magnitude of {}",
            case.input
        );
    }
}

#[test]
fn every_fold_agrees_with_the_reference() {
    // These come from the reference's own arithmetic library rather than from
    // a transcription of it: its sum reduces without a seed, its mean divides
    // by a plain count, and its median sorts with a comparator that returns a
    // BigNumber for the runtime to coerce. A transcription would have been
    // free to get those wrong in the same way the port does.
    for case in fixture().lists {
        let values: Vec<DecimalValue> =
            case.values.iter().map(|v| DecimalValue::parse(v)).collect();
        let context = case.values.join(", ");

        assert_eq!(
            bignumber::sum(&values).to_fixed(),
            case.sum,
            "the total of {context}"
        );
        assert_eq!(
            bignumber::mean(&values).to_fixed(),
            case.mean,
            "the mean of {context}"
        );
        assert_eq!(
            bignumber::median(&values).to_fixed(),
            case.median,
            "the median of {context}"
        );
    }
}

#[test]
fn every_reading_in_another_base_agrees_with_the_reference() {
    for case in fixture().base_parses {
        let read = bignumber::parse_in_base(&case.text, case.base);
        let context = format!("{:?} in base {}", case.text, case.base);
        match case.fixed {
            Some(expected) => assert_eq!(
                read.map(|value| value.to_fixed()),
                Some(expected),
                "reading {context}"
            ),
            None => assert!(
                read.is_none(),
                "reading {context} should be refused, and answered {:?}",
                read.map(|value| value.to_fixed())
            ),
        }
    }
}

#[test]
fn every_writing_in_another_base_agrees_with_the_reference() {
    for case in fixture().base_renders {
        let value = DecimalValue::parse(&case.input);
        let written = bignumber::to_base(&value, case.base);
        assert_eq!(
            written, case.written,
            "writing {} in base {}",
            case.input, case.base
        );
    }
}

#[test]
fn the_two_base_rules_run_backwards_from_the_ordinary_ones() {
    // Stated once here because a reader who knows the single-argument
    // constructor will expect the opposite of each of these, and the fixture
    // alone does not say which cases are the surprising ones.
    assert_eq!(
        bignumber::parse_in_base("", 16).map(|value| value.to_fixed()),
        Some("0".to_owned()),
        "an empty string is zero with a base, and refused without one"
    );
    assert!(
        DecimalValue::parse("").is_not_a_number(),
        "and refused without one"
    );

    assert!(
        bignumber::parse_in_base("Infinity", 16).is_none(),
        "a base refuses the specials, which the single-argument reading accepts"
    );
    assert!(DecimalValue::parse("Infinity").is_infinite());

    assert_eq!(
        bignumber::parse_in_base("1e5", 16).map(|value| value.to_fixed()),
        Some("485".to_owned()),
        "with a base, `e` is a digit rather than an exponent marker"
    );
    assert_eq!(DecimalValue::parse("1e5").to_fixed(), "100000");

    assert!(
        bignumber::parse_in_base("0xff", 16).is_none(),
        "a base refuses the prefix the single-argument reading requires"
    );
    assert_eq!(DecimalValue::parse("0xff").to_fixed(), "255");

    // And the writing: a base never turns exponential, where the argumentless
    // rendering does at the same value.
    let large = DecimalValue::parse("1e21");
    assert_eq!(
        bignumber::to_base(&large, 10).as_deref(),
        Some("1000000000000000000000")
    );
    assert_eq!(large.to_notation(), "1e+21");
}

#[test]
fn a_sum_is_exact_where_a_quotient_is_not() {
    // The asymmetry a port most easily gets wrong, stated as a test rather
    // than only as a comment: adding tenths is exact and dividing by three is
    // not, and both must be so.
    let tenth = DecimalValue::parse("0.1");
    let fifth = DecimalValue::parse("0.2");
    assert_eq!(
        bignumber::plus(&tenth, &fifth).to_fixed(),
        "0.3",
        "a sum carries no rounding at all"
    );

    let one = DecimalValue::parse("1");
    let three = DecimalValue::parse("3");
    assert_eq!(
        bignumber::divide(&one, &three).to_fixed(),
        "0.33333333333333333333",
        "a quotient stops at twenty places"
    );
}
