//! Replays the arithmetic of the reference's arbitrary-precision library.
//!
//! Rendering was pinned first and is the easy half: one value, one answer.
//! Arithmetic has a configuration, and the configuration is where a port goes
//! wrong quietly -- rounding a sum that should be exact, or failing to round a
//! quotient that should not be.
//!
//! The fixture is generated by `tools/cyberchef-oracle/bignumber.mjs` from the
//! library inside the pinned checkout, and carries the settings it was
//! produced under so a reader can see which rules the answers follow.

#![cfg(feature = "bignum")]

use ferrosift_model::DecimalValue;
use ferrosift_operations::jscompat_testing::bignumber;
use serde::Deserialize;

const FIXTURE: &str = include_str!("fixtures/bignumber.json");

#[derive(Deserialize)]
struct Fixture {
    settings: Settings,
    binary: Vec<Binary>,
    unary: Vec<Unary>,
    lists: Vec<List>,
}

#[derive(Deserialize)]
struct Settings {
    decimal_places: u32,
    rounding_mode: u32,
    modulo_mode: u32,
}

#[derive(Deserialize)]
struct Binary {
    left: String,
    right: String,
    plus: String,
    minus: String,
    times: String,
    div: String,
    #[serde(rename = "mod")]
    remainder: String,
}

#[derive(Deserialize)]
struct Unary {
    input: String,
    sqrt: String,
    negated: String,
    absolute: String,
}

#[derive(Deserialize)]
struct List {
    values: Vec<String>,
    sum: String,
    mean: String,
    median: String,
}

fn fixture() -> Fixture {
    serde_json::from_str(FIXTURE).expect("the oracle's fixture parses")
}

#[test]
fn the_settings_are_the_ones_this_port_was_written_against() {
    // If the reference is ever reconfigured, every answer below changes and
    // the failures would look like arithmetic bugs. Checking the settings
    // first turns that into one clear failure instead of thirty confusing
    // ones.
    let settings = fixture().settings;
    assert_eq!(settings.decimal_places, 20, "places carried");
    assert_eq!(settings.rounding_mode, 4, "half away from zero");
    assert_eq!(settings.modulo_mode, 1, "truncated, dividend's sign");
}

#[test]
fn every_binary_operation_agrees_with_the_reference() {
    for case in fixture().binary {
        let left = DecimalValue::parse(&case.left);
        let right = DecimalValue::parse(&case.right);
        let context = format!("{} and {}", case.left, case.right);

        assert_eq!(
            bignumber::plus(&left, &right).to_fixed(),
            case.plus,
            "adding {context}"
        );
        assert_eq!(
            bignumber::minus(&left, &right).to_fixed(),
            case.minus,
            "subtracting {context}"
        );
        assert_eq!(
            bignumber::times(&left, &right).to_fixed(),
            case.times,
            "multiplying {context}"
        );
        assert_eq!(
            bignumber::divide(&left, &right).to_fixed(),
            case.div,
            "dividing {context}"
        );
        assert_eq!(
            bignumber::modulo(&left, &right).to_fixed(),
            case.remainder,
            "the remainder of {context}"
        );
    }
}

#[test]
fn every_unary_operation_agrees_with_the_reference() {
    for case in fixture().unary {
        let value = DecimalValue::parse(&case.input);
        assert_eq!(
            bignumber::square_root(&value).to_fixed(),
            case.sqrt,
            "the root of {}",
            case.input
        );
        assert_eq!(
            bignumber::negate(&value).to_fixed(),
            case.negated,
            "negating {}",
            case.input
        );
        assert_eq!(
            bignumber::absolute(&value).to_fixed(),
            case.absolute,
            "the magnitude of {}",
            case.input
        );
    }
}

#[test]
fn every_fold_agrees_with_the_reference() {
    // These come from the reference's own arithmetic library rather than from
    // a transcription of it: its sum reduces without a seed, its mean divides
    // by a plain count, and its median sorts with a comparator that returns a
    // BigNumber for the runtime to coerce. A transcription would have been
    // free to get those wrong in the same way the port does.
    for case in fixture().lists {
        let values: Vec<DecimalValue> =
            case.values.iter().map(|v| DecimalValue::parse(v)).collect();
        let context = case.values.join(", ");

        assert_eq!(
            bignumber::sum(&values).to_fixed(),
            case.sum,
            "the total of {context}"
        );
        assert_eq!(
            bignumber::mean(&values).to_fixed(),
            case.mean,
            "the mean of {context}"
        );
        assert_eq!(
            bignumber::median(&values).to_fixed(),
            case.median,
            "the median of {context}"
        );
    }
}

#[test]
fn a_sum_is_exact_where_a_quotient_is_not() {
    // The asymmetry a port most easily gets wrong, stated as a test rather
    // than only as a comment: adding tenths is exact and dividing by three is
    // not, and both must be so.
    let tenth = DecimalValue::parse("0.1");
    let fifth = DecimalValue::parse("0.2");
    assert_eq!(
        bignumber::plus(&tenth, &fifth).to_fixed(),
        "0.3",
        "a sum carries no rounding at all"
    );

    let one = DecimalValue::parse("1");
    let three = DecimalValue::parse("3");
    assert_eq!(
        bignumber::divide(&one, &three).to_fixed(),
        "0.33333333333333333333",
        "a quotient stops at twenty places"
    );
}
