//! Replays what the reference's own arbitrary-precision library produced.
//!
//! `FerroSift` carries a decimal as a canonical sign, coefficient, and exponent
//! rather than by depending on `bignumber.js`, so the rendering is a
//! reproduction and has to be checked against the thing it reproduces. The
//! fixture is generated by `tools/cyberchef-oracle/decimal.mjs` from the real
//! library inside the pinned checkout -- not from its documentation, which
//! describes a constructor that returns not-a-number where the real one
//! throws.

use ferrosift_model::DecimalValue;

/// Every pair the reference produced, as `input`, `fixed`, `nan`, `rejected`.
const FIXTURE: &str = include_str!("fixtures/decimal.json");

/// One recorded case, read without a JSON library so the test has no
/// dependency the model itself does not carry.
struct Case {
    input: String,
    fixed: String,
    not_a_number: bool,
}

/// Reads the fixture's cases.
///
/// A hand-written reader rather than `serde_json`: the fixture's shape is
/// fixed by the generator beside it, and adding a parser here would mean the
/// test could fail for a reason that has nothing to do with decimals.
fn cases() -> Vec<Case> {
    let mut cases = Vec::new();
    for chunk in FIXTURE.split("\"input\":").skip(1) {
        let input = field(chunk, "").expect("every case has an input");
        let fixed = field(chunk, "\"fixed\":").expect("every case has a rendering");
        let not_a_number = chunk
            .split("\"nan\":")
            .nth(1)
            .is_some_and(|tail| tail.trim_start().starts_with("true"));
        cases.push(Case {
            input,
            fixed,
            not_a_number,
        });
    }
    cases
}

/// The next JSON string after `marker`, with its escapes resolved.
fn field(chunk: &str, marker: &str) -> Option<String> {
    let tail = if marker.is_empty() {
        chunk
    } else {
        chunk.split(marker).nth(1)?
    };
    let start = tail.find('"')? + 1;
    let mut output = String::new();
    let mut characters = tail[start..].chars();
    while let Some(character) = characters.next() {
        match character {
            '"' => return Some(output),
            '\\' => match characters.next()? {
                'n' => output.push('\n'),
                't' => output.push('\t'),
                other => output.push(other),
            },
            other => output.push(other),
        }
    }
    None
}

#[test]
fn renders_every_recorded_value_exactly() {
    let cases = cases();
    assert!(
        cases.len() >= 30,
        "fixture looks truncated: {} cases",
        cases.len()
    );
    for case in cases {
        let parsed = DecimalValue::parse(&case.input);
        assert_eq!(
            parsed.to_fixed(),
            case.fixed,
            "rendering {:?} disagreed with the reference",
            case.input
        );
        assert_eq!(
            parsed.is_not_a_number(),
            case.not_a_number,
            "not-a-number disagreed for {:?}",
            case.input
        );
    }
}

#[test]
fn values_that_print_alike_are_alike() {
    // Normalisation is not tidiness: the reference renders `1.000` as `1` and
    // `-0` as `0`, so two values that print the same have to compare equal or
    // equality would disagree with output.
    for (left, right) in [
        ("1.000", "1"),
        ("-0", "0"),
        ("0.0100", "0.01"),
        ("000123", "123"),
        ("1e2", "100"),
        ("0.1e1", "1"),
    ] {
        assert_eq!(
            DecimalValue::parse(left),
            DecimalValue::parse(right),
            "{left} and {right} print alike but did not compare equal"
        );
    }
}

#[test]
fn an_integer_becomes_the_same_number() {
    for value in [0_i128, 1, -1, i128::MAX, i128::MIN] {
        assert_eq!(
            DecimalValue::from(value).to_fixed(),
            value.to_string(),
            "an integer should render as itself"
        );
    }
}
