//! Replays what the reference's own arbitrary-precision library produced.
//!
//! `FerroSift` carries a decimal as a canonical sign, coefficient, and exponent
//! rather than by depending on `bignumber.js`, so the rendering is a
//! reproduction and has to be checked against the thing it reproduces. The
//! fixture is generated by `tools/cyberchef-oracle/decimal.mjs` from the real
//! library inside the pinned checkout -- not from its documentation, which
//! describes a constructor that returns not-a-number where the real one
//! throws.

use ferrosift_model::DecimalValue;

/// Every pair the reference produced, as `input`, `fixed`, `nan`, `rejected`.
const FIXTURE: &str = include_str!("fixtures/decimal.json");

/// One recorded case.
#[derive(serde::Deserialize)]
struct Case {
    input: String,
    fixed: String,
    #[serde(rename = "nan")]
    not_a_number: bool,
}

#[derive(serde::Deserialize)]
struct Fixture {
    cases: Vec<Case>,
}

/// Reads the fixture's cases.
///
/// This was a hand-written reader, on the reasoning that a parser here could
/// fail for a reason unrelated to decimals. It then failed for a reason
/// unrelated to decimals: it resolved `\n` and `\t` and not `\r`, so a case
/// carrying a carriage return was compared against text the fixture never
/// held. A real parser is the smaller risk.
fn cases() -> Vec<Case> {
    let fixture: Fixture = serde_json::from_str(FIXTURE).expect("the oracle's fixture parses");
    fixture.cases
}

#[test]
fn renders_every_recorded_value_exactly() {
    let cases = cases();
    assert!(
        cases.len() >= 30,
        "fixture looks truncated: {} cases",
        cases.len()
    );
    for case in cases {
        let parsed = DecimalValue::parse(&case.input);
        assert_eq!(
            parsed.to_fixed(),
            case.fixed,
            "rendering {:?} disagreed with the reference",
            case.input
        );
        assert_eq!(
            parsed.is_not_a_number(),
            case.not_a_number,
            "not-a-number disagreed for {:?}",
            case.input
        );
    }
}

#[test]
fn values_that_print_alike_are_alike() {
    // Normalisation is not tidiness: the reference renders `1.000` as `1` and
    // `-0` as `0`, so two values that print the same have to compare equal or
    // equality would disagree with output.
    for (left, right) in [
        ("1.000", "1"),
        ("-0", "0"),
        ("0.0100", "0.01"),
        ("000123", "123"),
        ("1e2", "100"),
        ("0.1e1", "1"),
    ] {
        assert_eq!(
            DecimalValue::parse(left),
            DecimalValue::parse(right),
            "{left} and {right} print alike but did not compare equal"
        );
    }
}

#[test]
fn an_integer_becomes_the_same_number() {
    for value in [0_i128, 1, -1, i128::MAX, i128::MIN] {
        assert_eq!(
            DecimalValue::from(value).to_fixed(),
            value.to_string(),
            "an integer should render as itself"
        );
    }
}

#[test]
fn an_exponent_past_the_range_becomes_infinite_rather_than_enormous() {
    // The reference keeps a normalised exponent up to ten million and answers
    // infinity beyond it, so the largest thing it will ever render is bounded.
    // Without the clamp, eleven characters of source would describe a number
    // whose rendering is a hundred megabytes.
    assert_eq!(DecimalValue::parse("1e100000000").to_fixed(), "Infinity");
    assert_eq!(DecimalValue::parse("-1e100000000").to_fixed(), "-Infinity");
    assert_eq!(DecimalValue::parse("1e-100000000").to_fixed(), "0");
}

#[test]
fn a_large_value_is_measured_without_being_rendered() {
    // Inside the range and still far too large to build while measuring: a
    // budget asks for the size before deciding, and rendering it to answer
    // would make the allocation the budget exists to refuse.
    let value = DecimalValue::parse("1e9999999");
    assert_eq!(value.rendered_len(), 10_000_000);
}

#[test]
fn the_measured_length_is_the_rendered_length() {
    // The arithmetic mirrors `to_fixed` branch for branch, so every branch is
    // checked against the thing it predicts.
    for input in [
        "0",
        "-0",
        "1",
        "-1",
        "42",
        "1.5",
        "-1.5",
        "0.001",
        "-0.001",
        "1e10",
        "-1e10",
        "1e-10",
        "-1e-10",
        "123456789012345678901234567890",
        "NaN",
        "Infinity",
        "-Infinity",
        "abc",
    ] {
        let value = DecimalValue::parse(input);
        assert_eq!(
            value.rendered_len(),
            value.to_fixed().len() as u64,
            "the predicted length disagreed with the rendering for {input:?}"
        );
    }
}
