// Emits the unit tables the five Convert operations are built on.
//
// Transcribed by a machine rather than by hand, for two reasons that are not
// laziness. The tables are a hundred and eighty-nine entries across five
// operations, and a single mistyped digit would be a wrong answer for one unit
// pair out of several hundred -- the kind of thing a sampled corpus can miss
// entirely.
//
// The second reason is subtler and matters more. Each factor is a JavaScript
// *number* literal, and the reference multiplies a BigNumber by it. What
// BigNumber actually receives is the double's shortest decimal representation,
// which is what `String(value)` produces here -- not the literal as written in
// the source. For most entries the two agree; for any that do not, copying the
// source text would be copying the wrong number. So the value recorded is what
// the reference would have used, taken from the reference.
//
// The output is Rust, not JSON: these tables ship inside a `no_std` crate and
// parsing them at startup would be work done on every process for data that
// never changes.

import {writeFileSync} from "node:fs";
import path from "node:path";
import {fileURLToPath} from "node:url";

import {selectedProfile, verifyCheckout} from "./reference.mjs";

const checkout = verifyCheckout(selectedProfile());

/** The five operations, and the names their tables go by inside each. */
const TABLES = [
    {module: "ConvertArea", units: "AREA_UNITS", factor: "AREA_FACTOR", rust: "AREA"},
    {module: "ConvertDataUnits", units: "DATA_UNITS", factor: "DATA_FACTOR", rust: "DATA"},
    {module: "ConvertDistance", units: "DISTANCE_UNITS", factor: "DISTANCE_FACTOR", rust: "DISTANCE"},
    {module: "ConvertMass", units: "MASS_UNITS", factor: "MASS_FACTOR", rust: "MASS"},
    {module: "ConvertSpeed", units: "SPEED_UNITS", factor: "SPEED_FACTOR", rust: "SPEED"},
];

/**
 * Reads one table out of an operation's source.
 *
 * The tables are module-level constants that the module does not export, so
 * they are evaluated out of the source text rather than imported. Only the two
 * `const` declarations are evaluated -- not the operation class, which would
 * drag in the whole reference.
 */
async function read(entry) {
    const file = path.join(checkout, "src/core/operations", `${entry.module}.mjs`);
    const source = await import(
        new URL(`file://${file}`).href
    ).then(() => null).catch(() => null);
    // The import above is only to surface a module that fails to load at all;
    // the values come from the text, because they are not exported.
    void source;

    const text = await import("node:fs/promises").then(fs => fs.readFile(file, "utf8"));
    const factor = extract(text, entry.factor);
    return {...entry, factor};
}

/** Evaluates one `const NAME = { ... };` object out of a module's source. */
function extract(text, name) {
    const at = text.indexOf(`const ${name}`);
    if (at < 0) throw new Error(`no ${name} in source`);
    const open = text.indexOf("{", at);
    let depth = 0;
    let end = open;
    for (; end < text.length; end += 1) {
        if (text[end] === "{") depth += 1;
        else if (text[end] === "}") {
            depth -= 1;
            if (depth === 0) break;
        }
    }
    // eslint-disable-next-line no-new-func
    return Function(`"use strict"; return (${text.slice(open, end + 1)});`)();
}

/** A Rust string literal, escaped for the two characters that need it. */
function literal(value) {
    return `"${value.replace(/\\/gu, "\\\\").replace(/"/gu, '\\"')}"`;
}

const tables = [];
for (const entry of TABLES) {
    tables.push(await read(entry));
}

let rust = `//! Unit tables for the five Convert operations.
//!
//! Generated by \`tools/cyberchef-oracle/units.mjs\` from the pinned checkout.
//! Do not edit by hand: a hundred and eighty-nine factors is more than anyone
//! should retype, and the value here is the *double's* shortest decimal form
//! rather than the literal as written in the reference's source -- which is
//! what the reference's arithmetic actually receives, and is not always the
//! same text.
//!
//! Each factor converts its unit to the group's base unit. A conversion is
//! therefore a multiplication by the input's factor and a division by the
//! output's, in that order, which is what the reference does and is not the
//! same as one combined ratio: the division rounds.

`;

for (const table of tables) {
    const entries = Object.entries(table.factor);
    rust += `/// ${table.rust.charAt(0)}${table.rust.slice(1).toLowerCase()} units, `
        + `${entries.length} of them.\n`;
    rust += `pub(crate) const ${table.rust}: &[(&str, &str)] = &[\n`;
    for (const [unit, value] of entries) {
        rust += `    (${literal(unit)}, ${literal(String(value))}),\n`;
    }
    rust += "];\n\n";
}

const output = path.resolve(
    path.dirname(fileURLToPath(import.meta.url)),
    "../../crates/ferrosift-operations/src/convert/units.rs",
);
writeFileSync(output, rust, "utf8");
process.stdout.write(
    `wrote ${tables.reduce((sum, t) => sum + Object.keys(t.factor).length, 0)} factors `
        + `across ${tables.length} tables to ${output}\n`,
);
