//! Replays what `ImHex`'s own runtime answered for the same source and bytes.
//!
//! The other sixty-six tests in this crate ask the crate what the crate does.
//! This one asks whether the crate agrees with the implementation it follows,
//! which is a different question and the only one a compatibility claim can
//! rest on. The fixture is generated by `tools/pattern-oracle/generate.mjs`
//! from a pinned checkout of `WerWolv/PatternLanguage`.
//!
//! Where the two disagree, the disagreement is recorded in [`DIVERGENCES`]
//! together with what *this* crate answers. That is deliberately stricter than
//! skipping the case: a listed divergence fails if either side moves, so
//! neither an upstream change nor a local one can pass unnoticed.

use ferrosift_pattern::{EvalOptions, Node, NodeValue};
use serde::Deserialize;

const FIXTURE: &str = include_str!("fixtures/imhex.json");

#[derive(Deserialize)]
struct Fixture {
    reference: Reference,
    cases: Vec<Case>,
}

#[derive(Deserialize)]
struct Reference {
    commit: String,
}

#[derive(Deserialize)]
struct Case {
    name: String,
    pattern: String,
    data: String,
    json: String,
}

/// Cases where this crate answers something else, and what it answers.
///
/// Every entry is a decision this crate made knowingly, not a defect waiting
/// to be found. Each records the reason, so a reader deciding whether to close
/// the gap has the argument rather than only the symptom.
const DIVERGENCES: &[(&str, &str)] = &[
    // The reference reads bitfield members from the least significant bit of a
    // little-endian span; this crate reads from the most significant bit of a
    // big-endian one. `docs/pattern-language-subset.md` documented that as this
    // crate's own layout before there was anything to compare it against.
    (
        "bitfield_member_order",
        "{\n    \"flags\": {\n        \"low\": 5,\n        \"high\": 5\n    }\n}",
    ),
    (
        "bitfield_across_two_bytes",
        "{\n    \"wide\": {\n        \"a\": 1,\n        \"b\": 35,\n        \"c\": 4\n    }\n}",
    ),
];

#[test]
fn agrees_with_the_reference_or_diverges_exactly_as_recorded() {
    let fixture: Fixture = serde_json::from_str(FIXTURE).expect("the oracle's fixture parses");
    assert!(
        !fixture.reference.commit.is_empty(),
        "the fixture must name the commit it came from"
    );
    assert!(
        fixture.cases.len() >= 12,
        "fixture looks truncated: {} cases",
        fixture.cases.len()
    );

    let mut agreed = 0;
    let mut diverged = 0;
    for case in &fixture.cases {
        let pattern = ferrosift_pattern::parse(&case.pattern)
            .unwrap_or_else(|error| panic!("{} did not parse: {error:?}", case.name));
        let data = decode_hex(&case.data);
        let nodes = ferrosift_pattern::evaluate(&pattern, &data, &EvalOptions::default())
            .unwrap_or_else(|error| panic!("{} did not evaluate: {error:?}", case.name));
        let ours = render(&nodes);
        let theirs = case.json.trim_end();

        if let Some((_, recorded)) = DIVERGENCES.iter().find(|(name, _)| *name == case.name) {
            assert_ne!(
                ours, theirs,
                "{} is listed as a divergence but now agrees; remove the entry",
                case.name
            );
            assert_eq!(
                ours, *recorded,
                "{} diverges differently than recorded",
                case.name
            );
            diverged += 1;
        } else {
            assert_eq!(ours, theirs, "{} disagreed with the reference", case.name);
            agreed += 1;
        }
    }

    assert_eq!(
        diverged,
        DIVERGENCES.len(),
        "every recorded divergence must appear in the fixture"
    );
    assert!(agreed > 0, "no case actually agreed");
}

/// Renders evaluated nodes into the shape the reference's JSON formatter uses.
///
/// Comparing renderings rather than internals is the point: reaching past
/// either side to its own tree would compare two designs instead of two
/// answers.
fn render(nodes: &[Node]) -> String {
    let mut output = String::from("{\n");
    for (index, node) in nodes.iter().enumerate() {
        if index > 0 {
            output.push_str(",\n");
        }
        output.push_str("    ");
        output.push_str(&quote(&node.name));
        output.push_str(": ");
        output.push_str(&render_node(node, 1));
    }
    output.push_str("\n}");
    output
}

/// One node, indented to sit at `depth`.
fn render_node(node: &Node, depth: usize) -> String {
    match &node.value {
        NodeValue::Unsigned(value) => value.to_string(),
        NodeValue::Signed(value) => value.to_string(),
        NodeValue::Bool(value) => String::from(if *value { "true" } else { "false" }),
        NodeValue::Char(value) => quote(&value.to_string()),
        NodeValue::Float(value) => render_float(f64::from(*value)),
        NodeValue::Double(value) => render_float(*value),
        NodeValue::Enumerator { name, .. } => {
            // An unmatched value is `Type::???` there; here the name is absent
            // and the rendering supplies the same marker so the two shapes can
            // be compared at all.
            let constant = name.as_deref().unwrap_or("???");
            quote(&alloc_format(&node.type_name, constant))
        }
        NodeValue::Group(children) => {
            if node.type_name.ends_with(']') {
                render_array(children, depth)
            } else {
                render_object(children, depth)
            }
        }
    }
}

/// `Type::Constant`, the way the reference spells an enumerator.
fn alloc_format(type_name: &str, constant: &str) -> String {
    let mut output = String::with_capacity(type_name.len() + constant.len() + 2);
    output.push_str(type_name);
    output.push_str("::");
    output.push_str(constant);
    output
}

/// A JSON array of the children, or `[]` when there are none.
fn render_array(children: &[Node], depth: usize) -> String {
    if children.is_empty() {
        return String::from("[]");
    }
    let inner = depth + 1;
    let mut output = String::from("[\n");
    for (index, child) in children.iter().enumerate() {
        if index > 0 {
            output.push_str(",\n");
        }
        output.push_str(&"    ".repeat(inner));
        output.push_str(&render_node(child, inner));
    }
    output.push('\n');
    output.push_str(&"    ".repeat(depth));
    output.push(']');
    output
}

/// A JSON object keyed by each child's name.
fn render_object(children: &[Node], depth: usize) -> String {
    if children.is_empty() {
        return String::from("{}");
    }
    let inner = depth + 1;
    let mut output = String::from("{\n");
    for (index, child) in children.iter().enumerate() {
        if index > 0 {
            output.push_str(",\n");
        }
        output.push_str(&"    ".repeat(inner));
        output.push_str(&quote(&child.name));
        output.push_str(": ");
        output.push_str(&render_node(child, inner));
    }
    output.push('\n');
    output.push_str(&"    ".repeat(depth));
    output.push('}');
    output
}

/// A float as the reference prints one: a whole value carries no point.
fn render_float(value: f64) -> String {
    if value.is_finite() && value.fract() == 0.0 {
        // A whole value carries no point there, and `{:.0}` writes exactly
        // that without leaving the float type to do it.
        return format!("{value:.0}");
    }
    format!("{value}")
}

/// A JSON string with the escapes the reference's formatter emits.
fn quote(text: &str) -> String {
    let mut output = String::with_capacity(text.len() + 2);
    output.push('"');
    for character in text.chars() {
        match character {
            '"' => output.push_str("\\\""),
            '\\' => output.push_str("\\\\"),
            '\n' => output.push_str("\\n"),
            other => output.push(other),
        }
    }
    output.push('"');
    output
}

/// Reads the fixture's hex payloads.
fn decode_hex(text: &str) -> Vec<u8> {
    text.as_bytes()
        .chunks(2)
        .filter(|pair| pair.len() == 2)
        .map(|pair| {
            let value = |byte: u8| char::from(byte).to_digit(16).unwrap_or(0);
            u8::try_from(value(pair[0]) * 16 + value(pair[1])).unwrap_or(0)
        })
        .collect()
}
