//! Replays what `ImHex`'s own runtime answered for the same source and bytes.
//!
//! The other sixty-six tests in this crate ask the crate what the crate does.
//! This one asks whether the crate agrees with the implementation it follows,
//! which is a different question and the only one a compatibility claim can
//! rest on. The fixture is generated by `tools/pattern-oracle/generate.mjs`
//! from a pinned checkout of `WerWolv/PatternLanguage`.
//!
//! Where the two disagree, the disagreement is recorded in [`DIVERGENCES`]
//! together with what *this* crate answers. That is deliberately stricter than
//! skipping the case: a listed divergence fails if either side moves, so
//! neither an upstream change nor a local one can pass unnoticed.

use ferrosift_pattern::{Builtin, EvalOptions, Node, NodeValue};
use serde::Deserialize;

const FIXTURE: &str = include_str!("fixtures/imhex.json");

#[derive(Deserialize)]
struct Fixture {
    reference: Reference,
    cases: Vec<Case>,
}

#[derive(Deserialize)]
struct Reference {
    commit: String,
}

#[derive(Deserialize)]
struct Case {
    name: String,
    pattern: String,
    data: String,
    json: String,
}

/// Cases where this crate answers something else, and what it answers.
///
/// Empty, and the emptiness is checked rather than assumed — every case in the
/// fixture that runs is compared against the reference byte for byte, so an
/// entry here would have to be added deliberately.
///
/// The two that used to be here were the bitfield layout, which this crate had
/// chosen for itself before there was an implementation to compare against.
/// The reference's rule is that bit order follows byte order; reading
/// most-significant-first from a big-endian span unconditionally was right for
/// half the cases, and nothing was gained by keeping it for the other half.
const DIVERGENCES: &[(&str, &str)] = &[];

/// Cases the reference runs and this crate cannot, with the code it answers.
///
/// Kept in the fixture rather than deleted from it. A case the corpus does not
/// hold is a gap nobody can see; a case that is held and asserted to fail is a
/// gap with a name, a reproduction, and a test that will notice the day it
/// closes. The entry is as strict as a passing case: implementing the feature
/// fails this test until the entry goes.
const UNSUPPORTED: &[(&str, &str)] = &[
    // `sizeof` takes a built-in type or a field already read. A declared type
    // has a size too, and computing it means walking the declaration rather
    // than the tree that was read -- which is a different question for a type
    // whose own arrays are variable-length.
    ("sizeof_type", "pattern.eval.unknown_field"),
    ("sizeof_nested_struct", "pattern.eval.unknown_field"),
];

#[test]
fn agrees_with_the_reference_or_diverges_exactly_as_recorded() {
    let fixture: Fixture = serde_json::from_str(FIXTURE).expect("the oracle's fixture parses");
    assert!(
        !fixture.reference.commit.is_empty(),
        "the fixture must name the commit it came from"
    );
    // The generator writes what the reference agreed to run, so a case it
    // refuses is silently dropped rather than reported as a failure. A floor
    // here is what turns "the fixture got smaller" into a test result.
    assert!(
        fixture.cases.len() >= 100,
        "fixture looks truncated: {} cases",
        fixture.cases.len()
    );

    let mut agreed = 0;
    let mut diverged = 0;
    let mut unsupported = 0;
    for case in &fixture.cases {
        let data = decode_hex(&case.data);
        let outcome = ferrosift_pattern::parse(&case.pattern).and_then(|pattern| {
            ferrosift_pattern::evaluate(&pattern, &data, &EvalOptions::default())
        });

        if let Some((_, code)) = UNSUPPORTED.iter().find(|(name, _)| *name == case.name) {
            let error = outcome.err().unwrap_or_else(|| {
                panic!(
                    "{} is listed as unsupported but now runs; remove the entry",
                    case.name
                )
            });
            assert_eq!(
                error.code(),
                *code,
                "{} fails differently than recorded",
                case.name
            );
            unsupported += 1;
            continue;
        }

        let nodes = outcome.unwrap_or_else(|error| panic!("{} did not run: {error:?}", case.name));
        let ours = render(&nodes);
        let theirs = case.json.trim_end();

        if let Some((_, recorded)) = DIVERGENCES.iter().find(|(name, _)| *name == case.name) {
            assert_ne!(
                ours, theirs,
                "{} is listed as a divergence but now agrees; remove the entry",
                case.name
            );
            assert_eq!(
                ours, *recorded,
                "{} diverges differently than recorded",
                case.name
            );
            diverged += 1;
        } else {
            assert_eq!(ours, theirs, "{} disagreed with the reference", case.name);
            agreed += 1;
        }
    }

    assert_eq!(
        diverged,
        DIVERGENCES.len(),
        "every recorded divergence must appear in the fixture"
    );
    assert_eq!(
        unsupported,
        UNSUPPORTED.len(),
        "every recorded gap must appear in the fixture"
    );
    assert!(agreed > 0, "no case actually agreed");
}

/// Renders evaluated nodes into the shape the reference's JSON formatter uses.
///
/// Comparing renderings rather than internals is the point: reaching past
/// either side to its own tree would compare two designs instead of two
/// answers.
fn render(nodes: &[Node]) -> String {
    let mut output = String::from("{\n");
    for (index, node) in nodes.iter().enumerate() {
        if index > 0 {
            output.push_str(",\n");
        }
        output.push_str("    ");
        output.push_str(&quote(&node.name));
        output.push_str(": ");
        output.push_str(&render_node(node, 1));
    }
    output.push_str("\n}");
    output
}

/// One node, indented to sit at `depth`.
fn render_node(node: &Node, depth: usize) -> String {
    match &node.value {
        NodeValue::Unsigned(value) => value.to_string(),
        NodeValue::Signed(value) => value.to_string(),
        NodeValue::Bool(value) => String::from(if *value { "true" } else { "false" }),
        NodeValue::Char(value) => quote(&value.to_string()),
        NodeValue::Float(value) => render_float(f64::from(*value)),
        NodeValue::Double(value) => render_float(*value),
        NodeValue::Enumerator { name, .. } => {
            // An unmatched value is `Type::???` there; here the name is absent
            // and the rendering supplies the same marker so the two shapes can
            // be compared at all.
            let constant = name.as_deref().unwrap_or("???");
            quote(&alloc_format(&node.type_name, constant))
        }
        NodeValue::Group(children) => {
            // An array of `char` is one string there, not a list of
            // one-character ones. That is the formatter's choice and not a
            // difference in what was read, so it belongs here rather than in
            // the crate: both sides hold the same five characters.
            if !children.is_empty()
                && children
                    .iter()
                    .all(|child| matches!(child.value, NodeValue::Char(_)))
            {
                let text: String = children
                    .iter()
                    .map(|child| match child.value {
                        NodeValue::Char(value) => value,
                        _ => unreachable!("every child was checked above"),
                    })
                    .collect();
                return quote(&text);
            }
            if node.type_name.ends_with(']') {
                render_array(children, depth)
            } else {
                render_object(children, depth)
            }
        }
        NodeValue::Scalars(array) => {
            // The same two renderings as a group of scalars would get. Which
            // representation the crate happens to use for an array of built-in
            // elements is a decision about memory, and the reference's output
            // cannot see it — so this arm exists to prove exactly that: the
            // JSON either side produces is unchanged by it.
            if array.element_type() == Builtin::Char {
                let text: String = array
                    .iter()
                    .map(|value| match value {
                        NodeValue::Char(character) => character,
                        _ => unreachable!("the element type was checked to be char"),
                    })
                    .collect();
                return quote(&text);
            }
            let elements: Vec<String> = array
                .iter()
                .map(|value| {
                    render_node(
                        &Node {
                            name: String::new(),
                            type_name: String::new(),
                            offset: 0,
                            size: 0,
                            value,
                        },
                        depth + 1,
                    )
                })
                .collect();
            render_values(&elements, depth)
        }
    }
}

/// `Type::Constant`, the way the reference spells an enumerator.
fn alloc_format(type_name: &str, constant: &str) -> String {
    let mut output = String::with_capacity(type_name.len() + constant.len() + 2);
    output.push_str(type_name);
    output.push_str("::");
    output.push_str(constant);
    output
}

/// A JSON array of the children.
///
/// An empty one still opens and closes on two lines, because the reference's
/// formatter writes the newline before it knows whether anything follows.
fn render_array(children: &[Node], depth: usize) -> String {
    let inner = depth + 1;
    let elements: Vec<String> = children
        .iter()
        .map(|child| render_node(child, inner))
        .collect();
    render_values(&elements, depth)
}

/// A JSON array of already-rendered elements.
///
/// Shared by the two array representations so neither can drift into its own
/// formatting, which would show up as a compatibility failure that was really
/// a test bug.
fn render_values(elements: &[String], depth: usize) -> String {
    if elements.is_empty() {
        return format!("[\n{}]", "    ".repeat(depth));
    }
    let inner = depth + 1;
    let mut output = String::from("[\n");
    for (index, element) in elements.iter().enumerate() {
        if index > 0 {
            output.push_str(",\n");
        }
        output.push_str(&"    ".repeat(inner));
        output.push_str(element);
    }
    output.push('\n');
    output.push_str(&"    ".repeat(depth));
    output.push(']');
    output
}

/// A JSON object keyed by each child's name, empty ones on two lines like the
/// arrays above.
fn render_object(children: &[Node], depth: usize) -> String {
    if children.is_empty() {
        return format!("{{\n{}}}", "    ".repeat(depth));
    }
    let inner = depth + 1;
    let mut output = String::from("{\n");
    for (index, child) in children.iter().enumerate() {
        if index > 0 {
            output.push_str(",\n");
        }
        output.push_str(&"    ".repeat(inner));
        output.push_str(&quote(&child.name));
        output.push_str(": ");
        output.push_str(&render_node(child, inner));
    }
    output.push('\n');
    output.push_str(&"    ".repeat(depth));
    output.push('}');
    output
}

/// A float as the reference prints one: a whole value carries no point.
fn render_float(value: f64) -> String {
    if value.is_finite() && value.fract() == 0.0 {
        // A whole value carries no point there, and `{:.0}` writes exactly
        // that without leaving the float type to do it.
        return format!("{value:.0}");
    }
    format!("{value}")
}

/// A JSON string with the escapes the reference's formatter emits.
fn quote(text: &str) -> String {
    let mut output = String::with_capacity(text.len() + 2);
    output.push('"');
    for character in text.chars() {
        match character {
            '"' => output.push_str("\\\""),
            '\\' => output.push_str("\\\\"),
            '\n' => output.push_str("\\n"),
            other => output.push(other),
        }
    }
    output.push('"');
    output
}

/// Reads the fixture's hex payloads.
fn decode_hex(text: &str) -> Vec<u8> {
    text.as_bytes()
        .chunks(2)
        .filter(|pair| pair.len() == 2)
        .map(|pair| {
            let value = |byte: u8| char::from(byte).to_digit(16).unwrap_or(0);
            u8::try_from(value(pair[0]) * 16 + value(pair[1])).unwrap_or(0)
        })
        .collect()
}
