// The safety matrix: what a caller exposing an operation to untrusted input
// needs to know about it.
//
// The compatibility ledger answers "does this match the reference". This
// answers a different question that nothing else did: *what can this operation
// do*. Four properties, all declared beside the operation and none of them
// inferable from its name — which host capabilities it requires, what a
// reviewer classified it as, whether it is deterministic, and how its output
// relates to its input.
//
// Derived from the live catalog for the same reason the ledger is: a
// hand-written safety table is a claim about code that the code cannot
// contradict, and this is the one document where that would matter most.
import {execFileSync} from "node:child_process";
import {readFileSync, writeFileSync} from "node:fs";
import path from "node:path";
import {fileURLToPath} from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, "../..");

/** The whole catalog, as the CLI reports it. */
function catalog() {
    const raw = execFileSync(
        "cargo",
        [
            "run",
            "--quiet",
            "-p",
            "ferrosift-cli",
            "--",
            "operations",
            "--format",
            "json",
        ],
        {cwd: repoRoot, encoding: "utf8", maxBuffer: 64 * 1024 * 1024},
    );
    return JSON.parse(raw.replace(/^﻿/, "")).operations;
}

/** What each classification means to someone deciding what to allow. */
const CLASSIFICATIONS = {
    unsafe: [
        "Needs an explicit policy decision",
        "Not a defect and not a warning about the implementation. These are "
            + "operations whose *purpose* is one a deployment may not want: a "
            + "broken cipher kept for reading old data, a decoder for a format "
            + "designed to hide things. Whether that is acceptable is a question "
            + "about the deployment, so it is surfaced rather than answered.",
    ],
    resource_intensive: [
        "Cost is set by an argument, not by the input",
        "Key derivations are the clear case: they are *designed* to be slow, "
            + "take how slow from a parameter, and return a short answer either "
            + "way — so neither the input nor the output says what running one "
            + "will cost. The declaration is advice; `max_work_units` and "
            + "`max_transient_bytes` are the enforcement, and they apply whether "
            + "or not an operation says this about itself.",
    ],
    legacy: [
        "Exists for compatibility with an obsolete format",
        "Correct, pinned, and not something to reach for in new work.",
    ],
    random: ["Output can depend on randomness", "Repeating it may not repeat."],
    external: [
        "Behaviour depends on an external system",
        "The answer is not a function of the input alone.",
    ],
};

/** What each output behaviour means for the expansion ratio. */
const BEHAVIOURS = {
    input_proportional: "Output grows with input; the expansion ratio applies",
    input_independent: "Output comes from the arguments; the ratio is not applied",
    reducer: "Output is a bounded summary; the ratio is not applied",
};

function tally(operations, field) {
    const counts = new Map();
    for (const operation of operations) {
        for (const value of operation[field]) {
            counts.set(value, (counts.get(value) ?? 0) + 1);
        }
    }
    return counts;
}

function render(operations) {
    const capabilities = tally(operations, "capabilities");
    const classifications = tally(operations, "classifications");
    const nondeterministic = operations.filter(one => !one.deterministic);
    const behaviours = new Map();
    for (const operation of operations) {
        behaviours.set(
            operation.output_behavior,
            (behaviours.get(operation.output_behavior) ?? 0) + 1,
        );
    }

    const lines = [
        "# Safety matrix",
        "",
        "Generated by `cargo xtask ledger generate`. Do not edit by hand: every",
        "row is derived from the live catalog, so it cannot describe a version of",
        "the code that does not exist.",
        "",
        "The [compatibility ledger](compatibility/ledger.md) answers whether an",
        "operation matches the reference. This answers a different question, and",
        "one a caller has to answer before the first: **what can this operation",
        "do?** Four properties, each declared beside the operation and none of",
        "them inferable from its name.",
        "",
        "## What the whole catalog requires",
        "",
        `| | |`,
        "|---|---:|",
        `| Registered operations | ${operations.length} |`,
        `| Requiring any host capability | ${capabilities.size === 0 ? 0 : [...capabilities.values()].reduce((a, b) => a + b, 0)} |`,
        `| Non-deterministic | ${nondeterministic.length} |`,
        `| Carrying any review classification | ${operations.filter(one => one.classifications.length > 0).length} |`,
        "",
    ];

    if (capabilities.size === 0) {
        lines.push(
            "**No operation requires a host capability.** Not one asks for the",
            "filesystem, the network, a clock, or a random source — so a caller",
            "granting nothing can run the entire catalog, and the grant list is a",
            "thing to keep empty rather than a thing to audit.",
            "",
            "That is a property of the portable core rather than a coincidence: it",
            "exposes no host handles at all, and an operation needing one would have",
            "to declare it here first. `HostCapability` exists so that the day one",
            "does, this table stops saying zero.",
            "",
        );
    } else {
        lines.push("| Host capability | Operations |", "|---|---:|");
        for (const [name, count] of [...capabilities].sort((a, b) => b[1] - a[1])) {
            lines.push(`| \`${name}\` | ${count} |`);
        }
        lines.push("");
    }

    if (nondeterministic.length === 0) {
        lines.push(
            "**Every operation is deterministic.** The same input and the same",
            "arguments produce the same bytes, on every run and every target — which",
            "is what makes the differential corpus a test rather than a sample.",
            "",
        );
    }

    lines.push(
        "## Review classifications",
        "",
        "A classification is a statement about the operation's *purpose*, not about",
        "the quality of its implementation. Every one of these is pinned against the",
        "reference like anything else.",
        "",
    );
    for (const [name, count] of [...classifications].sort((a, b) => b[1] - a[1])) {
        const [summary, detail] = CLASSIFICATIONS[name] ?? [name, ""];
        lines.push(`### \`${name}\` — ${count} operations`, "", `${summary}. ${detail}`, "");
        const named = operations
            .filter(one => one.classifications.includes(name))
            .map(one => `\`${one.id}\``);
        lines.push(named.join(", "), "");
    }

    lines.push(
        "## Output behaviour",
        "",
        "Which limit the executor applies to an operation's growth. The absolute",
        "output ceiling, the total-bytes accounting and cancellation apply to every",
        "one of them; only the *ratio* differs, and only where a ratio would measure",
        "nothing.",
        "",
        "| Behaviour | Operations | What it means |",
        "|---|---:|---|",
    );
    for (const [name, count] of [...behaviours].sort((a, b) => b[1] - a[1])) {
        lines.push(`| \`${name}\` | ${count} | ${BEHAVIOURS[name] ?? ""} |`);
    }
    lines.push(
        "",
        "Both exemptions are opt-in and checked. `tests/output_behavior.rs` names",
        "every generator, and runs every reducer over inputs differing by a factor",
        "of 256 to confirm it does not grow.",
        "",
        "## Every operation",
        "",
        "`—` where an operation declares nothing, which is most of them.",
        "",
        "| Operation | Capabilities | Classifications | Output |",
        "|---|---|---|---|",
    );
    for (const operation of operations) {
        const capability = operation.capabilities.length
            ? operation.capabilities.map(one => `\`${one}\``).join(", ")
            : "—";
        const classification = operation.classifications.length
            ? operation.classifications.map(one => `\`${one}\``).join(", ")
            : "—";
        lines.push(
            `| \`${operation.id}\` | ${capability} | ${classification} `
                + `| \`${operation.output_behavior}\` |`,
        );
    }
    lines.push("");
    return lines.join("\n");
}

export const matrixPath = path.join(repoRoot, "docs/safety-matrix.md");

export function buildMatrix() {
    return render(catalog());
}

/** True when the committed matrix is what the catalog produces. */
export function matrixIsCurrent(rendered) {
    let committed;
    try {
        committed = readFileSync(matrixPath, "utf8");
    } catch {
        return false;
    }
    return committed.replace(/\r\n/g, "\n") === rendered;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
    const rendered = buildMatrix();
    if (process.argv.includes("--check")) {
        if (!matrixIsCurrent(rendered)) {
            process.stderr.write(
                `${matrixPath} is stale\nrun: cargo xtask ledger generate\n`,
            );
            process.exit(1);
        }
        process.stdout.write("safety matrix current\n");
    } else {
        writeFileSync(matrixPath, rendered, "utf8");
        process.stdout.write(`wrote ${matrixPath}\n`);
    }
}
